# Generated by Django 4.2.26 on 2025-11-28 21:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_parent_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_by',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
